-- ============================================================================
--  The Diamonds League · contenido inicial de la base de datos
--  neptun / andres / Dvskked — github.com/Dvskked
--  Importa este archivo DESPUÉS de sql/esquema.sql
--  Generado desde el volcado de la versión anterior: 14 equipos, 70 partidos,
--  6 miembros del equipo, 4 bloques de reglas, 14 premios, 5 salas, 3 noticias,
--  2 anuncios, 2 divisiones.
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `ajustes`;
TRUNCATE TABLE `equipos`;
TRUNCATE TABLE `partidos`;
TRUNCATE TABLE `regla_items`;
TRUNCATE TABLE `reglas`;
TRUNCATE TABLE `salas`;
TRUNCATE TABLE `noticias`;
TRUNCATE TABLE `anuncios`;
TRUNCATE TABLE `premios`;
TRUNCATE TABLE `personal`;
TRUNCATE TABLE `destacados`;
TRUNCATE TABLE `alianzas`;
TRUNCATE TABLE `redes`;
TRUNCATE TABLE `directos`;
TRUNCATE TABLE `donaciones`;
TRUNCATE TABLE `divisiones`;

-- ---------------------------------------------------------------- Ajustes
INSERT INTO `ajustes` (`id`, `league_name`, `short_name`, `tagline`, `description`, `season`, `season_number`, `modality`, `status`, `status_note`, `server`, `map`, `match_duration`, `tolerance`, `points_win`, `points_draw`, `tiktok`, `tiktok_handle`, `founded`, `match_config`, `donation_note`, `donation_key`, `donation_goal`) VALUES (1, 'The Diamonds League', 'TDL', 'Liga competitiva de HaxBall X5', 'The Diamonds League es la liga competitiva de HaxBall X5 con 2 divisiones, 12 equipos en División 1, salas públicas abiertas y calendario oficial por jornadas.', 'Temporada 3', 3, '5 vs 5', 'ACTIVA', 'Temporada 3 en curso · Inscripciones abiertas', 'X Hosting', '5v5 Diamonds League', 'Dos tiempos de 10:00 + última jugada', '15 minutos', 3, 1, 'https://www.tiktok.com/@diamondsleague89?is_from_webapp=1&sender_device=pc', '@diamondsleague89', '2025', '[{"label":"Modalidad","value":"5 vs 5 · X5"},{"label":"Duración","value":"Dos tiempos de 10:00 + última jugada"},{"label":"Mapa","value":"5v5 Diamonds League"},{"label":"Servidor","value":"X Hosting"}]', 'Tus aportes pagan servidores, premios y material de la liga.', '', 0);

-- ------------------------------------------------------------- Divisiones
INSERT INTO `divisiones` (`id`, `name`, `code`, `season`, `summary`, `teams`, `journeys`, `playoffs`, `relegation`, `promotion`, `phases`, `movement`, `rules`, `sort_order`) VALUES ('d1', 'División 1', 'D1', 'Temporada 3', 'La categoría principal: 12 equipos, 11 jornadas y playoffs por el título.', 12, 11, 4, '2 descensos directos', 'Sin ascensos', '[{"label":"Fase 1","title":"Liga regular","text":"Todos contra todos durante 11 jornadas. Victoria 3 puntos, empate 1 punto y derrota 0 puntos.","note":"Clasifican a playoffs los puestos 1°, 2°, 3° y 4°."},{"label":"Fase 2","title":"Playoffs","text":"Semifinal 1: 1° vs 4°. Semifinal 2: 2° vs 3°.","note":"Semifinales a un partido. Final de ida y vuelta."}]', '{"title":"Descenso","items":[{"place":"11° lugar","label":"Descenso directo","text":"Baja a División 2 al terminar la liga regular."},{"place":"12° lugar","label":"Descenso directo","text":"Baja a División 2 al terminar la liga regular."}]}', '[{"title":"Tolerancia","text":"15 minutos antes de aplicar W.O."},{"title":"W.O.","text":"Se aplica si un equipo no presenta mínimo 4 jugadores."},{"title":"Respeto","text":"Cero toxicidad durante los partidos y en los canales de la liga."},{"title":"Resultado y replay","text":"Al terminar el partido es obligatorio enviar el resultado y la repetición."}]', 0);
INSERT INTO `divisiones` (`id`, `name`, `code`, `season`, `summary`, `teams`, `journeys`, `playoffs`, `relegation`, `promotion`, `phases`, `movement`, `rules`, `sort_order`) VALUES ('d2', 'División 2', 'D2', 'Temporada 3', '8 equipos, 7 jornadas, playoffs y dos ascensos a División 1.', 8, 7, 4, 'Sin descenso', '2 ascensos', '[{"label":"Liga","title":"Liga regular","text":"Todos contra todos durante 7 jornadas. Victoria 3 puntos, empate 1 punto y derrota 0 puntos.","note":"Clasifican los puestos 1, 2, 3 y 4."},{"label":"Fase final","title":"Playoffs","text":"2° vs 3° y 4° vs 1°. Las semifinales son únicamente de ida.","note":"La final se juega ida y vuelta."}]', '{"title":"Ascensos","items":[{"place":"Primer ascenso","label":"1° lugar de la liga","text":"Ascenso directo a División 1."},{"place":"Segundo ascenso","label":"Ganador de los Playoffs","text":"El campeón de playoffs siempre asciende."}]}', '[{"title":"Tolerancia","text":"15 minutos."},{"title":"W.O.","text":"Se aplica si un equipo no presenta mínimo 4 jugadores."},{"title":"Resultados","text":"Se debe enviar captura y replay."}]', 1);

-- ---------------------------------------------------------------- Equipos
INSERT INTO `equipos` (`id`, `name`, `division`, `coach`, `colors`, `note`, `sort_order`) VALUES ('d1-1', 'MASCAPITOS-FC', 'd1', '', '["",""]', '', 0);
INSERT INTO `equipos` (`id`, `name`, `division`, `coach`, `colors`, `note`, `sort_order`) VALUES ('d1-2', 'KIOSCO-FC', 'd1', '', '["",""]', '', 1);
INSERT INTO `equipos` (`id`, `name`, `division`, `coach`, `colors`, `note`, `sort_order`) VALUES ('d1-3', 'PEQUEÑOS-HERMANOS', 'd1', '', '["",""]', '', 2);
INSERT INTO `equipos` (`id`, `name`, `division`, `coach`, `colors`, `note`, `sort_order`) VALUES ('d1-4', 'ORENSE', 'd1', '', '["",""]', '', 3);
INSERT INTO `equipos` (`id`, `name`, `division`, `coach`, `colors`, `note`, `sort_order`) VALUES ('d1-5', 'SKYLINE-SC', 'd1', '', '["",""]', '', 4);
INSERT INTO `equipos` (`id`, `name`, `division`, `coach`, `colors`, `note`, `sort_order`) VALUES ('d1-6', 'LIGA-DEPORTIVA-ALAJUELENSE', 'd1', '', '["",""]', '', 5);
INSERT INTO `equipos` (`id`, `name`, `division`, `coach`, `colors`, `note`, `sort_order`) VALUES ('d1-7', 'KLOKAN-FC', 'd1', '', '["",""]', '', 6);
INSERT INTO `equipos` (`id`, `name`, `division`, `coach`, `colors`, `note`, `sort_order`) VALUES ('d1-8', 'LEXINGTON', 'd1', '', '["",""]', '', 7);
INSERT INTO `equipos` (`id`, `name`, `division`, `coach`, `colors`, `note`, `sort_order`) VALUES ('d1-9', 'FRC-CLUB', 'd1', '', '["",""]', '', 8);
INSERT INTO `equipos` (`id`, `name`, `division`, `coach`, `colors`, `note`, `sort_order`) VALUES ('d1-10', 'PARCEROS-FC', 'd1', '', '["",""]', '', 9);
INSERT INTO `equipos` (`id`, `name`, `division`, `coach`, `colors`, `note`, `sort_order`) VALUES ('d1-11', 'CHELSEA', 'd1', '', '["",""]', '', 10);
INSERT INTO `equipos` (`id`, `name`, `division`, `coach`, `colors`, `note`, `sort_order`) VALUES ('d1-12', 'MYSTIC-STORM', 'd1', '', '["",""]', '', 11);
INSERT INTO `equipos` (`id`, `name`, `division`, `coach`, `colors`, `note`, `sort_order`) VALUES ('d2-1', 'DEPORTIVO PEREIRA', 'd2', 'DT Inuv', '["",""]', 'Campeón División 2 · Temporada 2', 12);
INSERT INTO `equipos` (`id`, `name`, `division`, `coach`, `colors`, `note`, `sort_order`) VALUES ('d2-2', 'KIOSKO FC', 'd2', '', '["",""]', 'Guante de Oro · Temporada 2', 13);

-- --------------------------------------------------------------- Partidos
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-1', 'd1', 'liga', 1, 'Jornada 1', '03/08 · 04/08', '2026-08-03', '19:00', 'MASCAPITOS-FC', 'KIOSCO-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-2', 'd1', 'liga', 1, 'Jornada 1', '03/08 · 04/08', '2026-08-03', '19:45', 'PEQUEÑOS-HERMANOS', 'ORENSE', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-3', 'd1', 'liga', 1, 'Jornada 1', '03/08 · 04/08', '2026-08-03', '20:30', 'SKYLINE-SC', 'LIGA-DEPORTIVA-ALAJUELENSE', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-4', 'd1', 'liga', 1, 'Jornada 1', '03/08 · 04/08', '2026-08-04', '19:00', 'KLOKAN-FC', 'LEXINGTON', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-5', 'd1', 'liga', 1, 'Jornada 1', '03/08 · 04/08', '2026-08-04', '19:45', 'FRC-CLUB', 'PARCEROS-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-6', 'd1', 'liga', 1, 'Jornada 1', '03/08 · 04/08', '2026-08-04', '20:30', 'CHELSEA', 'MYSTIC-STORM', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-7', 'd1', 'liga', 2, 'Jornada 2', '05/08 · 06/08', '2026-08-05', '19:00', 'KIOSCO-FC', 'LIGA-DEPORTIVA-ALAJUELENSE', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-8', 'd1', 'liga', 2, 'Jornada 2', '05/08 · 06/08', '2026-08-05', '19:45', 'PEQUEÑOS-HERMANOS', 'LEXINGTON', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-9', 'd1', 'liga', 2, 'Jornada 2', '05/08 · 06/08', '2026-08-05', '20:30', 'SKYLINE-SC', 'PARCEROS-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-10', 'd1', 'liga', 2, 'Jornada 2', '05/08 · 06/08', '2026-08-06', '19:00', 'KLOKAN-FC', 'MYSTIC-STORM', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-11', 'd1', 'liga', 2, 'Jornada 2', '05/08 · 06/08', '2026-08-06', '19:45', 'FRC-CLUB', 'CHELSEA', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-12', 'd1', 'liga', 2, 'Jornada 2', '05/08 · 06/08', '2026-08-06', '20:30', 'MASCAPITOS-FC', 'ORENSE', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-13', 'd1', 'liga', 3, 'Jornada 3', '10/08 · 11/08', '2026-08-10', '19:00', 'KIOSCO-FC', 'PARCEROS-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-14', 'd1', 'liga', 3, 'Jornada 3', '10/08 · 11/08', '2026-08-10', '19:45', 'PEQUEÑOS-HERMANOS', 'MYSTIC-STORM', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-15', 'd1', 'liga', 3, 'Jornada 3', '10/08 · 11/08', '2026-08-10', '20:30', 'SKYLINE-SC', 'CHELSEA', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-16', 'd1', 'liga', 3, 'Jornada 3', '10/08 · 11/08', '2026-08-11', '19:00', 'KLOKAN-FC', 'FRC-CLUB', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-17', 'd1', 'liga', 3, 'Jornada 3', '10/08 · 11/08', '2026-08-11', '19:45', 'MASCAPITOS-FC', 'LIGA-DEPORTIVA-ALAJUELENSE', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-18', 'd1', 'liga', 3, 'Jornada 3', '10/08 · 11/08', '2026-08-11', '20:30', 'ORENSE', 'LEXINGTON', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-19', 'd1', 'liga', 4, 'Jornada 4', '12/08 · 13/08', '2026-08-12', '19:00', 'KIOSCO-FC', 'CHELSEA', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-20', 'd1', 'liga', 4, 'Jornada 4', '12/08 · 13/08', '2026-08-12', '19:45', 'PEQUEÑOS-HERMANOS', 'FRC-CLUB', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-21', 'd1', 'liga', 4, 'Jornada 4', '12/08 · 13/08', '2026-08-12', '20:30', 'SKYLINE-SC', 'KLOKAN-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-22', 'd1', 'liga', 4, 'Jornada 4', '12/08 · 13/08', '2026-08-13', '19:00', 'MASCAPITOS-FC', 'LEXINGTON', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-23', 'd1', 'liga', 4, 'Jornada 4', '12/08 · 13/08', '2026-08-13', '19:45', 'LIGA-DEPORTIVA-ALAJUELENSE', 'PARCEROS-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-24', 'd1', 'liga', 4, 'Jornada 4', '12/08 · 13/08', '2026-08-13', '20:30', 'ORENSE', 'MYSTIC-STORM', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-25', 'd1', 'liga', 5, 'Jornada 5', '17/08 · 18/08', '2026-08-17', '19:00', 'KIOSCO-FC', 'KLOKAN-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-26', 'd1', 'liga', 5, 'Jornada 5', '17/08 · 18/08', '2026-08-17', '19:45', 'PEQUEÑOS-HERMANOS', 'SKYLINE-SC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-27', 'd1', 'liga', 5, 'Jornada 5', '17/08 · 18/08', '2026-08-17', '20:30', 'MASCAPITOS-FC', 'PARCEROS-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-28', 'd1', 'liga', 5, 'Jornada 5', '17/08 · 18/08', '2026-08-18', '19:00', 'LEXINGTON', 'MYSTIC-STORM', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-29', 'd1', 'liga', 5, 'Jornada 5', '17/08 · 18/08', '2026-08-18', '19:45', 'LIGA-DEPORTIVA-ALAJUELENSE', 'CHELSEA', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-30', 'd1', 'liga', 5, 'Jornada 5', '17/08 · 18/08', '2026-08-18', '20:30', 'ORENSE', 'FRC-CLUB', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-31', 'd1', 'liga', 6, 'Jornada 6', '19/08 · 20/08', '2026-08-19', '19:00', 'KIOSCO-FC', 'PEQUEÑOS-HERMANOS', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-32', 'd1', 'liga', 6, 'Jornada 6', '19/08 · 20/08', '2026-08-19', '19:45', 'MASCAPITOS-FC', 'MYSTIC-STORM', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-33', 'd1', 'liga', 6, 'Jornada 6', '19/08 · 20/08', '2026-08-19', '20:30', 'PARCEROS-FC', 'CHELSEA', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-34', 'd1', 'liga', 6, 'Jornada 6', '19/08 · 20/08', '2026-08-20', '19:00', 'LEXINGTON', 'FRC-CLUB', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-35', 'd1', 'liga', 6, 'Jornada 6', '19/08 · 20/08', '2026-08-20', '19:45', 'LIGA-DEPORTIVA-ALAJUELENSE', 'KLOKAN-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-36', 'd1', 'liga', 6, 'Jornada 6', '19/08 · 20/08', '2026-08-20', '20:30', 'ORENSE', 'SKYLINE-SC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-37', 'd1', 'liga', 7, 'Jornada 7', '24/08 · 25/08', '2026-08-24', '19:00', 'MASCAPITOS-FC', 'CHELSEA', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-38', 'd1', 'liga', 7, 'Jornada 7', '24/08 · 25/08', '2026-08-24', '19:45', 'MYSTIC-STORM', 'FRC-CLUB', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-39', 'd1', 'liga', 7, 'Jornada 7', '24/08 · 25/08', '2026-08-24', '20:30', 'PARCEROS-FC', 'KLOKAN-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-40', 'd1', 'liga', 7, 'Jornada 7', '24/08 · 25/08', '2026-08-25', '19:00', 'LEXINGTON', 'SKYLINE-SC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-41', 'd1', 'liga', 7, 'Jornada 7', '24/08 · 25/08', '2026-08-25', '19:45', 'LIGA-DEPORTIVA-ALAJUELENSE', 'PEQUEÑOS-HERMANOS', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-42', 'd1', 'liga', 7, 'Jornada 7', '24/08 · 25/08', '2026-08-25', '20:30', 'ORENSE', 'KIOSCO-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-43', 'd1', 'liga', 8, 'Jornada 8', '26/08 · 27/08', '2026-08-26', '19:00', 'CHELSEA', 'KLOKAN-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-44', 'd1', 'liga', 8, 'Jornada 8', '26/08 · 27/08', '2026-08-26', '19:45', 'MYSTIC-STORM', 'SKYLINE-SC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-45', 'd1', 'liga', 8, 'Jornada 8', '26/08 · 27/08', '2026-08-26', '20:30', 'PARCEROS-FC', 'PEQUEÑOS-HERMANOS', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-46', 'd1', 'liga', 8, 'Jornada 8', '26/08 · 27/08', '2026-08-27', '19:00', 'LEXINGTON', 'KIOSCO-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-47', 'd1', 'liga', 8, 'Jornada 8', '26/08 · 27/08', '2026-08-27', '19:45', 'LIGA-DEPORTIVA-ALAJUELENSE', 'ORENSE', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-48', 'd1', 'liga', 8, 'Jornada 8', '26/08 · 27/08', '2026-08-27', '20:30', 'MASCAPITOS-FC', 'FRC-CLUB', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-49', 'd1', 'liga', 9, 'Jornada 9', '31/08 · 01/09', '2026-08-31', '19:00', 'CHELSEA', 'PEQUEÑOS-HERMANOS', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-50', 'd1', 'liga', 9, 'Jornada 9', '31/08 · 01/09', '2026-08-31', '19:45', 'MYSTIC-STORM', 'KIOSCO-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-51', 'd1', 'liga', 9, 'Jornada 9', '31/08 · 01/09', '2026-08-31', '20:30', 'PARCEROS-FC', 'ORENSE', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-52', 'd1', 'liga', 9, 'Jornada 9', '31/08 · 01/09', '2026-09-01', '19:00', 'LEXINGTON', 'LIGA-DEPORTIVA-ALAJUELENSE', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-53', 'd1', 'liga', 9, 'Jornada 9', '31/08 · 01/09', '2026-09-01', '19:45', 'MASCAPITOS-FC', 'KLOKAN-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-54', 'd1', 'liga', 9, 'Jornada 9', '31/08 · 01/09', '2026-09-01', '20:30', 'FRC-CLUB', 'SKYLINE-SC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-55', 'd1', 'liga', 10, 'Jornada 10', '02/09 · 03/09', '2026-09-02', '19:00', 'CHELSEA', 'ORENSE', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-56', 'd1', 'liga', 10, 'Jornada 10', '02/09 · 03/09', '2026-09-02', '19:45', 'MYSTIC-STORM', 'LIGA-DEPORTIVA-ALAJUELENSE', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-57', 'd1', 'liga', 10, 'Jornada 10', '02/09 · 03/09', '2026-09-02', '20:30', 'PARCEROS-FC', 'LEXINGTON', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-58', 'd1', 'liga', 10, 'Jornada 10', '02/09 · 03/09', '2026-09-03', '19:00', 'MASCAPITOS-FC', 'SKYLINE-SC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-59', 'd1', 'liga', 10, 'Jornada 10', '02/09 · 03/09', '2026-09-03', '19:45', 'KLOKAN-FC', 'PEQUEÑOS-HERMANOS', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-60', 'd1', 'liga', 10, 'Jornada 10', '02/09 · 03/09', '2026-09-03', '20:30', 'FRC-CLUB', 'KIOSCO-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-61', 'd1', 'liga', 11, 'Jornada 11', '07/09 · 08/09', '2026-09-07', '19:00', 'CHELSEA', 'LEXINGTON', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-62', 'd1', 'liga', 11, 'Jornada 11', '07/09 · 08/09', '2026-09-07', '19:45', 'MYSTIC-STORM', 'PARCEROS-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-63', 'd1', 'liga', 11, 'Jornada 11', '07/09 · 08/09', '2026-09-07', '20:30', 'MASCAPITOS-FC', 'PEQUEÑOS-HERMANOS', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-64', 'd1', 'liga', 11, 'Jornada 11', '07/09 · 08/09', '2026-09-08', '19:00', 'SKYLINE-SC', 'KIOSCO-FC', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-65', 'd1', 'liga', 11, 'Jornada 11', '07/09 · 08/09', '2026-09-08', '19:45', 'KLOKAN-FC', 'ORENSE', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-66', 'd1', 'liga', 11, 'Jornada 11', '07/09 · 08/09', '2026-09-08', '20:30', 'FRC-CLUB', 'LIGA-DEPORTIVA-ALAJUELENSE', NULL, NULL, 'programado', '', '');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-67', 'd1', 'playoffs', NULL, 'SF1', '', '2026-09-10', '19:00', '1° D1', '4° D1', NULL, NULL, 'por-definir', '', 'Cuadros de playoffs por confirmar al cerrar la liga regular.');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-68', 'd1', 'playoffs', NULL, 'SF2', '', '2026-09-10', '20:15', '2° D1', '3° D1', NULL, NULL, 'por-definir', '', 'Cuadros de playoffs por confirmar al cerrar la liga regular.');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-69', 'd1', 'playoffs', NULL, 'FINAL (IDA)', '', '2026-09-13', '19:00', 'Ganador SF1', 'Ganador SF2', NULL, NULL, 'por-definir', '', 'Cuadros de playoffs por confirmar al cerrar la liga regular.');
INSERT INTO `partidos` (`id`, `division`, `stage`, `journey`, `journey_label`, `range`, `date`, `time`, `home`, `away`, `home_goals`, `away_goals`, `status`, `replay`, `notes`) VALUES ('md1-70', 'd1', 'playoffs', NULL, 'FINAL (VUELTA)', '', '2026-09-14', '19:00', 'Ganador SF2', 'Ganador SF1', NULL, NULL, 'por-definir', '', 'Cuadros de playoffs por confirmar al cerrar la liga regular.');

-- ---------------------------------------------------------------- Reglas
INSERT INTO `reglas` (`id`, `title`, `summary`, `sort_order`) VALUES ('discord', 'Discord', 'Normas de convivencia dentro del servidor de la liga.', 0);
INSERT INTO `regla_items` (`rule_id`, `kind`, `text`, `sort_order`) VALUES ('discord', 'item', '{"title":"Respeto ante todo","text":"Respeta a todos los miembros, staff y admins. Cualquier falta de respeto será sancionada."}', 0);
INSERT INTO `regla_items` (`rule_id`, `kind`, `text`, `sort_order`) VALUES ('discord', 'item', '{"title":"Prohibido el spam","text":"No enviar mensajes repetitivos, links sin permiso o flood."}', 1);
INSERT INTO `regla_items` (`rule_id`, `kind`, `text`, `sort_order`) VALUES ('discord', 'item', '{"title":"Cumplir indicaciones del staff","text":"Las decisiones del staff deben respetarse en todo momento."}', 2);
INSERT INTO `regla_items` (`rule_id`, `kind`, `text`, `sort_order`) VALUES ('discord', 'item', '{"title":"Cero toxicidad","text":"Quedan prohibidos los insultos, racismo, discriminación, acoso o provocaciones."}', 3);
INSERT INTO `regla_items` (`rule_id`, `kind`, `text`, `sort_order`) VALUES ('discord', 'item', '{"title":"Contenido adecuado","text":"No se permite contenido NSFW, gore o inapropiado."}', 4);
INSERT INTO `regla_items` (`rule_id`, `kind`, `text`, `sort_order`) VALUES ('discord', 'item', '{"title":"Uso correcto de canales","text":"Habla en los canales correspondientes y evita el desorden."}', 5);
INSERT INTO `regla_items` (`rule_id`, `kind`, `text`, `sort_order`) VALUES ('discord', 'item', '{"title":"Publicidad con autorización","text":"Partners o promociones solo con autorización del staff."}', 6);
INSERT INTO `reglas` (`id`, `title`, `summary`, `sort_order`) VALUES ('comunidad', 'Comunidad', 'La forma en la que nos comportamos dentro y fuera del juego.', 1);
INSERT INTO `regla_items` (`rule_id`, `kind`, `text`, `sort_order`) VALUES ('comunidad', 'item', '{"title":"Buena conducta","text":"Mantén un ambiente sano y competitivo."}', 0);
INSERT INTO `regla_items` (`rule_id`, `kind`, `text`, `sort_order`) VALUES ('comunidad', 'item', '{"title":"Evitar conflictos","text":"Los problemas personales deben resolverse por privado o con staff."}', 1);
INSERT INTO `regla_items` (`rule_id`, `kind`, `text`, `sort_order`) VALUES ('comunidad', 'item', '{"title":"No suplantación","text":"Está prohibido hacerse pasar por otro usuario o staff."}', 2);
INSERT INTO `regla_items` (`rule_id`, `kind`, `text`, `sort_order`) VALUES ('comunidad', 'item', '{"title":"Nombres y perfiles adecuados","text":"No usar nombres ofensivos o provocativos."}', 3);
INSERT INTO `reglas` (`id`, `title`, `summary`, `sort_order`) VALUES ('division', 'División 1', 'Formato de competición, descenso y configuración de partidos.', 2);
INSERT INTO `regla_items` (`rule_id`, `kind`, `title`, `subtitle`, `text`, `list`, `sort_order`) VALUES ('division', 'bloque', 'Formato de competición', 'Liga regular y playoffs', 'Participan 12 equipos y se juega una vuelta de todos contra todos durante 11 jornadas.', '["Victoria: 3 puntos.","Empate: 1 punto.","Derrota: 0 puntos.","Clasifican los puestos 1°, 2°, 3° y 4°.","Semifinales: 1° vs 4° y 2° vs 3°, únicamente de ida.","Final: ida y vuelta."]', 0);
INSERT INTO `regla_items` (`rule_id`, `kind`, `title`, `subtitle`, `text`, `list`, `sort_order`) VALUES ('division', 'bloque', 'Sistema de descenso', 'Dos descensos directos', '', '["11° lugar: desciende directamente a División 2.","12° lugar: desciende directamente a División 2."]', 1);
INSERT INTO `regla_items` (`rule_id`, `kind`, `title`, `subtitle`, `text`, `list`, `sort_order`) VALUES ('division', 'bloque', 'Configuración de partidos', 'Formato oficial X5', '', '["Modalidad: 5v5.","Duración: dos tiempos de 10:00 minutos más última jugada.","Mapa: 5v5 Diamonds League.","Servidor: X Hosting."]', 2);
INSERT INTO `regla_items` (`rule_id`, `kind`, `title`, `subtitle`, `text`, `list`, `sort_order`) VALUES ('division', 'bloque', 'Reglas generales', 'Antes y después del partido', '', '["Tolerancia de 15 minutos.","W.O. si un equipo no presenta mínimo 4 jugadores.","Respeto obligatorio y cero toxicidad.","Es obligatorio enviar resultado y replay."]', 3);
INSERT INTO `reglas` (`id`, `title`, `summary`, `sort_order`) VALUES ('sanciones', 'Sanciones', 'Escala disciplinaria aplicada por el staff de la liga.', 3);
INSERT INTO `regla_items` (`rule_id`, `kind`, `title`, `kicker`, `tone`, `text`, `list`, `sort_order`) VALUES ('sanciones', 'tarjeta', 'Escala general', 'Comunidad', 'info', 'Las sanciones dependerán de la gravedad de la falta.', '["Advertencia o Warn","Silencio o Mute","Expulsión o Kick","Baneo o Ban"]', 0);
INSERT INTO `regla_items` (`rule_id`, `kind`, `title`, `kicker`, `tone`, `text`, `list`, `sort_order`) VALUES ('sanciones', 'tarjeta', 'Amarilla', 'Tarjeta', 'warn', '2 amarillas equivalen a 1 roja.', '["Conductas antideportivas","Pausas incorrectas","Reclamaciones excesivas"]', 1);
INSERT INTO `regla_items` (`rule_id`, `kind`, `title`, `kicker`, `tone`, `text`, `list`, `sort_order`) VALUES ('sanciones', 'tarjeta', 'Roja', 'Tarjeta', 'danger', 'Sanción más posible suspensión.', '["Insultos graves","Falta de respeto","Conducta antideportiva grave"]', 2);

-- ----------------------------------------------------------------- Salas
INSERT INTO `salas` (`id`, `label`, `name`, `url`, `status`, `players`, `note`) VALUES ('room-1', 'Room 01', 'Diamonds Public', 'https://www.haxball.com/play?c=lnjqtRG-Z-E', 'ABIERTA', NULL, '');
INSERT INTO `salas` (`id`, `label`, `name`, `url`, `status`, `players`, `note`) VALUES ('room-2', 'Room 02', 'Diamonds Public', 'https://www.haxball.com/play?c=lX3wqk3eNlo', 'ABIERTA', NULL, '');
INSERT INTO `salas` (`id`, `label`, `name`, `url`, `status`, `players`, `note`) VALUES ('room-3', 'Room 03', 'Diamonds Public', 'https://www.haxball.com/play?c=1ziccjYd2JU', 'ABIERTA', NULL, '');
INSERT INTO `salas` (`id`, `label`, `name`, `url`, `status`, `players`, `note`) VALUES ('room-4', 'Room 04', 'Diamonds Public', 'https://www.haxball.com/play?c=cPP-NvFDXTc', 'ABIERTA', NULL, '');
INSERT INTO `salas` (`id`, `label`, `name`, `url`, `status`, `players`, `note`) VALUES ('room-5', 'Room 05', 'Diamonds Public', 'https://www.haxball.com/play?c=Fu5CTxD2F-s', 'ABIERTA', NULL, '');

-- -------------------------------------------------------------- Noticias
INSERT INTO `noticias` (`id`, `title`, `category`, `excerpt`, `body`, `date`, `author`, `image`, `pinned`) VALUES ('news-1', 'Nueva página de The Diamonds League', 'Portada', 'En esta página se reunirán los avisos, resultados, entrevistas y contenido de cada jornada.', 'Todo el contenido oficial de la liga vive aquí: calendario por jornadas, salas públicas, reglas, premios y comunicados. El panel de administración permite actualizar cada módulo sin tocar código.', '2026-07-27', 'Staff', '/assets/diamonds-logo.webp', 1);
INSERT INTO `noticias` (`id`, `title`, `category`, `excerpt`, `body`, `date`, `author`, `image`, `pinned`) VALUES ('news-2', 'Resumen de jornada', 'Periódico', 'Resultados, marcadores y resumen de cada jornada.', 'Publicamos el resumen de cada jornada con marcadores, goleadores y la mejor actuación del partido.', '2026-08-03', 'Staff', '', 0);
INSERT INTO `noticias` (`id`, `title`, `category`, `excerpt`, `body`, `date`, `author`, `image`, `pinned`) VALUES ('news-3', 'Entrevistas', 'Comunidad', 'Entrevistas con jugadores, capitanes, staff y personas de la comunidad.', 'Una conversación con los protagonistas de cada fecha: capitanes, jugadores y staff de The Diamonds League.', '2026-08-10', 'Staff', '', 0);

-- -------------------------------------------------------------- Anuncios
INSERT INTO `anuncios` (`id`, `kind`, `season`, `title`, `kicker`, `date`, `text`, `bullets`, `closing`, `warning`, `day`, `month`, `year`) VALUES ('ann-1', 'awards', 'Temporada 2', 'Premios de la Temporada 2', 'Ceremonia de premios', '2026-03-11', 'Se anuncian los ganadores de las principales categorías y los clubes campeones de cada división.', '["Balón de Oro · Mejor jugador","Bota de Oro · Máximo goleador","Guante de Oro · Mejor portero","Campeones de División 1 y División 2"]', 'Estos fueron los premios entregados al terminar la Temporada 2.', '', 0, 0, 0);
INSERT INTO `anuncios` (`id`, `kind`, `season`, `title`, `kicker`, `date`, `text`, `bullets`, `closing`, `warning`, `day`, `month`, `year`) VALUES ('ann-2', 'registration', 'Temporada 3', 'Inscripciones para la Temporada 3', 'Inscripciones', '2026-07-27', 'Las inscripciones para la Temporada 3 abren el lunes 27 de julio de 2026. Los equipos y jugadores interesados podrán registrarse para participar desde la primera jornada.', '[]', '', 'Cupos limitados. Revisa el servidor y los anuncios para conocer el proceso de registro.', 27, 7, 2026);

-- ------------------------------------------------------- Premios (museo)
INSERT INTO `premios` (`id`, `division`, `category`, `season`, `title`, `team`, `text`, `image`, `year`) VALUES ('aw-01', 'd2', 'premios', 'Temporada 2', 'Balón de Oro · Gabinho', 'Deportivo Pereira', '24 goles y 12 asistencias.', '/assets/announcements/d2-balon-de-oro.webp', 0);
INSERT INTO `premios` (`id`, `division`, `category`, `season`, `title`, `team`, `text`, `image`, `year`) VALUES ('aw-02', 'd2', 'premios', 'Temporada 2', 'Guante de Oro · Sxra', 'Kiosko FC', '87 minutos y 6 segundos de clean sheet.', '/assets/announcements/d2-guante-de-oro.webp', 0);
INSERT INTO `premios` (`id`, `division`, `category`, `season`, `title`, `team`, `text`, `image`, `year`) VALUES ('aw-03', 'd2', 'premios', 'Temporada 2', 'Bota de Oro · Gabinho', 'Deportivo Pereira', '24 goles en liga.', '/assets/announcements/d2-bota-de-oro.webp', 0);
INSERT INTO `premios` (`id`, `division`, `category`, `season`, `title`, `team`, `text`, `image`, `year`) VALUES ('aw-04', 'd1', 'premios', 'Temporada 2', 'Balón de Oro · Muñoz', 'Lexington', '38 goles, 11 asistencias y 7 partidos.', '/assets/announcements/d1-balon-de-oro.webp', 0);
INSERT INTO `premios` (`id`, `division`, `category`, `season`, `title`, `team`, `text`, `image`, `year`) VALUES ('aw-05', 'd1', 'premios', 'Temporada 2', 'Guante de Oro · Oblea Gatona', 'Lexington', '68 minutos y 15 segundos de clean sheet.', '/assets/announcements/d1-guante-de-oro.webp', 0);
INSERT INTO `premios` (`id`, `division`, `category`, `season`, `title`, `team`, `text`, `image`, `year`) VALUES ('aw-06', 'd1', 'premios', 'Temporada 2', 'Bota de Oro · Muñoz', 'Lexington', '38 goles en 7 partidos.', '/assets/announcements/d1-bota-de-oro.webp', 0);
INSERT INTO `premios` (`id`, `division`, `category`, `season`, `title`, `team`, `text`, `image`, `year`) VALUES ('aw-07', 'd2', 'rankings', 'Temporada 2', 'Ranking Balón de Oro D2', 'División 2', 'Top 5 oficial de la Temporada 2.', '/assets/announcements/d2-ranking-balon.webp', 0);
INSERT INTO `premios` (`id`, `division`, `category`, `season`, `title`, `team`, `text`, `image`, `year`) VALUES ('aw-08', 'd2', 'rankings', 'Temporada 2', 'Ranking Guante de Oro D2', 'División 2', 'Top 5 oficial de porteros de la Temporada 2.', '/assets/announcements/d2-ranking-guante.webp', 0);
INSERT INTO `premios` (`id`, `division`, `category`, `season`, `title`, `team`, `text`, `image`, `year`) VALUES ('aw-09', 'd2', 'rankings', 'Temporada 2', 'Ranking Bota de Oro D2', 'División 2', 'Top 5 oficial de goleadores de la Temporada 2.', '/assets/announcements/d2-ranking-bota.webp', 0);
INSERT INTO `premios` (`id`, `division`, `category`, `season`, `title`, `team`, `text`, `image`, `year`) VALUES ('aw-10', 'd1', 'rankings', 'Temporada 2', 'Ranking Balón de Oro D1', 'División 1', 'Top 5 oficial de la Temporada 2.', '/assets/announcements/d1-ranking-balon.webp', 0);
INSERT INTO `premios` (`id`, `division`, `category`, `season`, `title`, `team`, `text`, `image`, `year`) VALUES ('aw-11', 'd1', 'rankings', 'Temporada 2', 'Ranking Guante de Oro D1', 'División 1', 'Top 5 oficial de porteros de la Temporada 2.', '/assets/announcements/d1-ranking-guante.webp', 0);
INSERT INTO `premios` (`id`, `division`, `category`, `season`, `title`, `team`, `text`, `image`, `year`) VALUES ('aw-12', 'd1', 'rankings', 'Temporada 2', 'Ranking Bota de Oro D1', 'División 1', 'Top 5 oficial de goleadores de la Temporada 2.', '/assets/announcements/d1-ranking-bota.webp', 0);
INSERT INTO `premios` (`id`, `division`, `category`, `season`, `title`, `team`, `text`, `image`, `year`) VALUES ('aw-13', 'd2', 'campeones', 'Temporada 2', 'Mejor club D2 · Deportivo Pereira', 'DT Inuv', 'Campeón de División 2.', '/assets/announcements/d2-mejor-club.webp', 0);
INSERT INTO `premios` (`id`, `division`, `category`, `season`, `title`, `team`, `text`, `image`, `year`) VALUES ('aw-14', 'd1', 'campeones', 'Temporada 2', 'Mejor club D1 · Lexington', 'DT Santiago', 'Campeón de División 1.', '/assets/announcements/d1-mejor-club.webp', 0);

-- ------------------------------------------------------- Equipo (personal)
INSERT INTO `personal` (`id`, `name`, `username`, `role`, `bio`, `avatar`, `banner`, `focus`, `github`, `instagram`, `discord`, `available`, `tags`) VALUES ('st-1', 'STEFY', 'st_fxx', 'Owner', 'Owner de The Diamonds League.', '/assets/team/stefy-avatar.webp', '/assets/team/stefy-banner.webp', '', '', '', '', 0, '["Owner","Dirección"]');
INSERT INTO `personal` (`id`, `name`, `username`, `role`, `bio`, `avatar`, `banner`, `focus`, `github`, `instagram`, `discord`, `available`, `tags`) VALUES ('st-2', 'ZSHR08', 'zshr08', 'Master', 'Master del servidor.', '/assets/team/zshr08-avatar.webp', '/assets/team/zshr08-banner.webp', '', '', '', '', 0, '["Master"]');
INSERT INTO `personal` (`id`, `name`, `username`, `role`, `bio`, `avatar`, `banner`, `focus`, `github`, `instagram`, `discord`, `available`, `tags`) VALUES ('st-3', 'ZYROX', 'zyrox_0169', 'Staff', '', '/assets/team/zyrox-avatar.webp', '/assets/team/zyrox-banner.webp', '', '', '', '', 0, '["Staff"]');
INSERT INTO `personal` (`id`, `name`, `username`, `role`, `bio`, `avatar`, `banner`, `focus`, `github`, `instagram`, `discord`, `available`, `tags`) VALUES ('st-4', 'AYALA', 'juanayala_1', 'Staff', '', '/assets/team/ayala-avatar.webp', '/assets/team/ayala-banner.webp', '', '', '', '', 0, '["Staff"]');
INSERT INTO `personal` (`id`, `name`, `username`, `role`, `bio`, `avatar`, `banner`, `focus`, `github`, `instagram`, `discord`, `available`, `tags`) VALUES ('st-5', 'SHENLONG', 'stuncito923', 'Staff', '', '/assets/team/shenlong-avatar.webp', '/assets/team/shenlong-banner.webp', '', '', '', '', 0, '["Staff"]');
INSERT INTO `personal` (`id`, `name`, `username`, `role`, `bio`, `avatar`, `banner`, `focus`, `github`, `instagram`, `discord`, `available`, `tags`) VALUES ('st-6', 'NEPTUN', 'andresneptunzinho', 'DESARROLLADOR', 'Desarrollador web de la liga. Disponible para desarrollo de software, sitios web y aplicaciones a medida.', '/assets/team/neptun.jpg', '', 'Desarrollo web y software a medida', 'Dvskked', '_andres.nox', 'andresneptunzinho', 1, '["Desarrollador","Web","Disponible"]');

-- ------------------------------------------------- Accesos de la liga
INSERT INTO `destacados` (`id`, `title`, `description`, `kind`, `href`, `cta`, `sort_order`) VALUES ('imp-1', 'Estado de la liga', 'Temporada 3 activa · 2 divisiones · 12 equipos en D1', 'status', '#importante', 'Ver estado', 0);
INSERT INTO `destacados` (`id`, `title`, `description`, `kind`, `href`, `cta`, `sort_order`) VALUES ('imp-2', 'Reglamento', 'Discord, comunidad, partidos y sanciones', 'link', '#reglas', 'Abrir reglas', 1);
INSERT INTO `destacados` (`id`, `title`, `description`, `kind`, `href`, `cta`, `sort_order`) VALUES ('imp-3', 'Anuncios y premios', 'Premios T2 e inscripciones T3', 'link', '#anuncios', 'Ver anuncios', 2);
INSERT INTO `destacados` (`id`, `title`, `description`, `kind`, `href`, `cta`, `sort_order`) VALUES ('imp-4', 'Calendario oficial', '11 jornadas · 66 partidos · PDF descargable', 'link', '#fechas', 'Ver fechas', 3);
INSERT INTO `destacados` (`id`, `title`, `description`, `kind`, `href`, `cta`, `sort_order`) VALUES ('imp-5', 'Servers partners', '8 servidores aliados de la liga', 'external', 'https://discord.gg/8JTfxJy66K', 'Entrar', 4);
INSERT INTO `destacados` (`id`, `title`, `description`, `kind`, `href`, `cta`, `sort_order`) VALUES ('imp-6', 'Afiliación RushBet', 'Diamonds League × RushBet desde el 11·03·2026', 'external', 'https://discord.gg/kVAjgkeRsC', 'Entrar', 5);
INSERT INTO `destacados` (`id`, `title`, `description`, `kind`, `href`, `cta`, `sort_order`) VALUES ('imp-7', 'TikTok oficial', '@diamondsleague89', 'external', 'https://www.tiktok.com/@diamondsleague89?is_from_webapp=1&sender_device=pc', 'Seguir', 6);
INSERT INTO `destacados` (`id`, `title`, `description`, `kind`, `href`, `cta`, `sort_order`) VALUES ('imp-8', 'Staff y administración', 'Owner, master y staff de la liga', 'link', '#equipos', 'Ver equipo', 7);

-- -------------------------------------------------------------- Alianzas
INSERT INTO `alianzas` (`id`, `name`, `kind`, `description`, `href`, `cta`, `image`, `status`, `sort_order`) VALUES ('al-0b0a6c', 'Servers partners', 'partner', '8 servidores aliados de la liga', 'https://discord.gg/8JTfxJy66K', 'Entrar', '', 'activa', 0);
INSERT INTO `alianzas` (`id`, `name`, `kind`, `description`, `href`, `cta`, `image`, `status`, `sort_order`) VALUES ('al-93b0ca', 'Afiliación RushBet', 'afiliacion', 'Diamonds League × RushBet desde el 11·03·2026', 'https://discord.gg/kVAjgkeRsC', 'Entrar', '', 'activa', 1);
INSERT INTO `alianzas` (`id`, `name`, `kind`, `description`, `href`, `cta`, `image`, `status`, `sort_order`) VALUES ('al-f58433', 'TikTok oficial', 'partner', '@diamondsleague89', 'https://www.tiktok.com/@diamondsleague89?is_from_webapp=1&sender_device=pc', 'Seguir', '', 'activa', 2);
INSERT INTO `alianzas` (`id`, `name`, `kind`, `description`, `href`, `cta`, `image`, `status`, `sort_order`) VALUES ('al-pendiente', 'Próxima afiliación', 'proxima', 'Espacio reservado para la próxima marca que se una a la liga.', '', 'Próximamente', '', 'proxima', 3);

-- ----------------------------------------------------------------- Redes
INSERT INTO `redes` (`id`, `network`, `owner_name`, `handle`, `url`, `followers`, `is_streamer`, `sort_order`) VALUES ('rd-aa96b1', 'tiktok', 'The Diamonds League', '@diamondsleague89', 'https://www.tiktok.com/@diamondsleague89?is_from_webapp=1&sender_device=pc', 0, 0, 0);
INSERT INTO `redes` (`id`, `network`, `owner_name`, `handle`, `url`, `followers`, `is_streamer`, `sort_order`) VALUES ('rd-82db9d', 'twitch', 'The Diamonds League', 'diamondsleague', 'https://www.twitch.tv/diamondsleague', 0, 1, 1);
INSERT INTO `redes` (`id`, `network`, `owner_name`, `handle`, `url`, `followers`, `is_streamer`, `sort_order`) VALUES ('rd-394f70', 'instagram', 'The Diamonds League', 'diamonds.league', 'https://instagram.com/diamonds.league', 0, 0, 2);
INSERT INTO `redes` (`id`, `network`, `owner_name`, `handle`, `url`, `followers`, `is_streamer`, `sort_order`) VALUES ('rd-6089f1', 'youtube', 'The Diamonds League', '@diamondsleague', 'https://youtube.com/@diamondsleague', 0, 0, 3);
INSERT INTO `redes` (`id`, `network`, `owner_name`, `handle`, `url`, `followers`, `is_streamer`, `sort_order`) VALUES ('rd-aac40c', 'discord', 'The Diamonds League', 'discord.gg/8JTfxJy66K', 'https://discord.gg/8JTfxJy66K', 0, 0, 4);

-- ------------------------------------------------- Directos de fútbol
INSERT INTO `directos` (`id`, `league`, `home`, `away`, `home_score`, `away_score`, `channel`, `platform`, `url`, `viewer_count`, `starts_at`, `is_live`, `sort_order`) VALUES ('live-1', 'Premier League', 'Por definir', 'Por definir', '', '', 'twitch', 'twitch', 'https://www.twitch.tv/diamondsleague', 0, NULL, 0, 0); -- Añade el enlace del directo desde el panel cuando haya transmisión en vivo

-- ------------------------------------------------------------- Donaciones
INSERT INTO `donaciones` (`id`, `title`, `description`, `kind`, `amount`, `method`, `account`, `goal`, `raised`, `is_active`, `sort_order`) VALUES ('dn-info', 'Apoya a The Diamonds League', 'Tus aportes pagan los servidores, los premios y el material de la liga.', 'info', 0, 'Nequi · PSE · PayPal', '', 0, 0, 1, 0); -- Pendiente: pega aquí tus datos de pago desde el panel

-- ------------------------------------------------------------- Usuarios
-- Registra a los usuarios desde la web en /registro (o crea el primero aquí):
--   INSERT INTO `usuarios` (`username`,`email`,`password_hash`,`terms_accepted_at`)
--   VALUES ('tu_usuario','correo@ejemplo.com','$2y$10$/aqc2G/hONWokgo0fPKTcehgkLJuayYAm/pRs66vfJAPsqjS/jWUW', NOW());

SET FOREIGN_KEY_CHECKS = 1;

